### ISSUE TITLE
Can't generate allure report in ver. 1.2.6 

### ISSUE THREAD

**Issue by Dimatrain** [allure-framework/allure-codeception#41] opened 2018-02-02 20:42 UTC
Windows 7, 10
allure-codeception 1.2.6

After this example code:

> public function loginSuccessfully(AcceptanceTester $I)
>     {
>         $I->fillField('[name="text"]', "Codeception");
>         $I->click('Найти');
>         $I->comment('Перешли на сайт яндекса');
>         $I->comment('We are going on yandex');
>     }

I get allure result in xml:

`
<step start="1517603309475" stop="1517603309475" status="passed">
           <name>🰵񐰵񈰻𸠰߰Р񃰰𹱂 񟰾𴰵𺱃𰠼/name>
         </step>
         <step start="1517603309475" stop="1517603309475" status="passed">
           <name>we are going on yandex </name>
        </step>`

And when i run allure generate i get errors like:

`com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xf0 (at char #790, byte #37)`

In previous version 1.2.5 it works correctly.

**Comment by nicholascus** [comment] 2018-03-07 02:27
The problem is in [Codeception\Step::humanize()](https://github.com/Codeception/Codeception/blob/master/src/Codeception/Step.php#L239) function
``` 
    protected function humanize($text)
    {
        $text = preg_replace('/([A-Z]+)([A-Z][a-z])/', '\\1 \\2', $text);
        $text = preg_replace('/([a-z\d])([A-Z])/', '\\1 \\2', $text);
        $text = preg_replace('~\bdont\b~', 'don\'t', $text);
        return strtolower($text);
    }
```
It screws utf8 strings. Solution is to fix it there, e.g. by extending return statement as below
```
        if (!preg_match('!!u', $text)) {
            return strtolower($text);
        } else {
            return mb_strtolower($text);
        }
```

**Comment by nicholascus** [comment] 2018-03-07 12:35
https://github.com/Codeception/Codeception/pull/4850

**Comment by nicholascus** [comment] 2018-03-15 09:21
The issue was fixed in Codeception 2.4. Can you try your project new builds?
```
        "allure-framework/allure-codeception": "1.2.6",
        "codeception/codeception": "~2.4.x-dev",
```

**Comment by Dimatrain** [comment] 2018-03-15 13:59
@nicholascus Now it works correctly, thanks!

**Comment by vitalyzhakov** [comment] 2019-12-13 08:56
@baev , hello!
May be close this issue?

**Closed** 2022-02-17 14:06 UTC
